# Generated by Django 5.1.1 on 2024-10-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='categories',
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.category'),
        ),
    ]
