# Generated by Django 5.1.1 on 2024-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_collection_categories_collection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='google_drive_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Please add name', max_length=255, null=True, upload_to='', verbose_name='Image name'),
        ),
    ]
