# Generated by Django 5.1.1 on 2024-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Collection slug'),
        ),
    ]
