# Generated by Django 5.1.1 on 2024-10-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Category slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(help_text='Please add name', max_length=255, null=True, upload_to='', verbose_name='Image name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Collection slug'),
        ),
    ]
