# Generated by Django 5.1.1 on 2024-10-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_collection_google_drive_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='google_drive_folder_id',
            new_name='google_drive_folder_link',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='google_drive_id',
            new_name='url',
        ),
    ]
