# Generated by Django 5.1.1 on 2024-10-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_google_drive_folder_id_collection_google_drive_folder_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='google_drive_folder_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
