# Generated by Django 5.1.1 on 2024-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_photo_drive_folder_id_alter_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='google_drive_folder_download_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
