# Generated by Django 5.1.1 on 2024-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_collection_google_drive_folder_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='enable_folder_download',
            field=models.BooleanField(default=False, verbose_name='Enable folder download'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='google_drive_folder_download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
