# Generated by Django 5.1.1 on 2024-10-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_collection_enable_folder_download_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='drive_folder_id',
            new_name='google_drive_photo_id',
        ),
    ]
