# Generated by Django 5.1.1 on 2024-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
