# Generated by Django 5.1.1 on 2024-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_sitesetting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='behance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
