# Generated by Django 5.1.1 on 2024-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='section1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='section2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='section3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Profile Photo'),
        ),
    ]
