# Generated by Django 5.1.1 on 2024-11-01 10:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_about_section1_about_section2_about_section3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='section3_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='section3_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='section3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='text1_az',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text1_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text1_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text2_az',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text2_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text2_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=tinymce.models.HTMLField(),
        ),
    ]
