# Generated by Django 5.1.1 on 2024-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_about_description_az_about_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(help_text='Required and unique', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Required and unique', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Required and unique', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
    ]
