# Generated by Django 5.1.1 on 2024-11-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_favorites_delete_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='photo',
        ),
        migrations.CreateModel(
            name='FavoritePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.favorites')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.photo')),
            ],
        ),
    ]
