# Generated by Django 5.1.1 on 2024-11-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_favorites_photo_favoritephotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='myapp.collection'),
        ),
    ]
