# Generated by Django 5.1.1 on 2024-11-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_favorites_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorites', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.RemoveField(
            model_name='favoritephotos',
            name='favorites_id',
        ),
        migrations.AddField(
            model_name='favoritephotos',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
