# Generated by Django 5.1.1 on 2024-11-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_favoritephotos_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='slug',
        ),
    ]
