# Generated by Django 5.1.1 on 2024-11-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_favorites_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
