# Generated by Django 5.1.1 on 2024-11-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='slug',
        ),
        migrations.DeleteModel(
            name='FavoritePhotos',
        ),
    ]
