# Generated by Django 5.1.1 on 2024-11-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_favorites_slug_delete_favoritephotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
