# Generated by Django 5.1.1 on 2024-11-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_favorites_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='reason_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='reason_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='reason_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
