# Generated by Django 5.1.1 on 2024-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_favorites_reason_az_favorites_reason_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
